//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.20 at 10:03:01 AM SGT 
//


package com.nicordesigns.spring_ws_insurance;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nicordesigns.spring_ws_insurance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nicordesigns.spring_ws_insurance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InsuranceResponse }
     * 
     */
    public InsuranceResponse createInsuranceResponse() {
        return new InsuranceResponse();
    }

    /**
     * Create an instance of {@link InsuranceRequest }
     * 
     */
    public InsuranceRequest createInsuranceRequest() {
        return new InsuranceRequest();
    }

    /**
     * Create an instance of {@link ApplicantType }
     * 
     */
    public ApplicantType createApplicantType() {
        return new ApplicantType();
    }

    /**
     * Create an instance of {@link InsuranceInfoType }
     * 
     */
    public InsuranceInfoType createInsuranceInfoType() {
        return new InsuranceInfoType();
    }

    /**
     * Create an instance of {@link WidgetInfoType }
     * 
     */
    public WidgetInfoType createWidgetInfoType() {
        return new WidgetInfoType();
    }

}
